### ISSUE TITLE
API Bling v3

### ISSUE THREAD

**Issue by leobaldoneto** [AlexandreBellas/bling-erp-api#9]
O Bling disponibilizou a API v3 utilizando Oauth com suporte a criação de integrações com aplicativos públicos. Tem alguns novos endpoints e modelos também. O que acha de fazer um cliente para a versão nova?

Fonte: https://developer.bling.com.br

**Comment by AlexandreBellas** [comment]
Acho interessante pra caramba, @leobaldoneto! Estou há um tempo pensando em dar uma repaginada no projeto e implementar a biblioteca também para PHP e C#.

Caso haja interesse em contribuir no projeto, fique à vontade ;)

**Comment by leobaldoneto** [comment]
@AlexandreBellas 

Bacana! Como eles disponibilizaram um schema OpenAPI, consegui gerar um cliente de forma automática em um teste isolado de um endpoint.

O schema deles possuem alguns erros, mas acho válido seguir por esse caminho. É possível usar um gerador e fazer a lógica de autenticação por fora. O que acha desse caminho?

**Comment by AlexandreBellas** [comment]
É uma ideia bacana! Só me preocupo com as tipagens, já que a geração de código automática costuma tratar tudo como `any` hehe

Eu gastei mais tempo montando as interfaces de envio/retorno de cada entidade do que fazendo a lógica da chamada da API em si, e esse investimento valeu super a pena visto que funcionou muito bem para o que precisei.

Você sabe se, nesta geração, daria para construir automaticamente as tipagens? :pray: 

Outra dúvida: a geração automática tem como alvo quais linguagens?

**Comment by AlexandreBellas** [comment]
Iniciei a implementação na _branch_ `feature/update-api-version-to-v3`:
https://github.com/AlexandreBellas/bling-erp-api/tree/feature/update-api-version-to-v3

**Comment by ivoneijr** [comment]
Bom Demais Alexandre! To ansioso para usar isso! hahahah

**Comment by AlexandreBellas** [comment]
@ivoneijr também estou ansioso para liberar e poder usar também :laughing: 

fique à vontade para implementar Produtos! já avancei para mais da metade das entidades, e as últimas entidades parecem ser mais rápidas.

com o @ivoneijr implementando Produtos, estou pensando em implementar somente Pedidos de venda + Pedidos de compra, dar uma melhorada na autenticação e já disponibilizar a 5.0.0. o que acham?

**Comment by AlexandreBellas** [comment]
Pessoal, é com grande prazer que anuncio o lançamento da versão 5 da biblioteca. Finalizei todas as entidades hoje e já atualizei o NPM. :smile: 

Por conta disto, fecharei a _issue_. Obrigado pela participação de todos.

**Comment by joaoboettcher** [comment]
Bom dia, parabens pela iniciativa de vcs.
